#############################################################################
# Makefile for building: warmup.app/Contents/MacOS/warmup
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  minecraft.pro
# Template: app
# Command: /Users/veenavignale/Qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile minecraft.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Qt/5.4/clang_64/mkspecs/macx-clang -I. -Isrc -I../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I. -F/Users/veenavignale/Qt/5.4/clang_64/lib
QMAKE         = /Users/veenavignale/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = warmup1.0.0
DISTDIR = /Users/veenavignale/Desktop/minecraft3/.tmp/warmup1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/veenavignale/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/veenavignale/Qt/5.4/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/common_engine/camera.cpp \
		src/common_engine/player.cpp \
		src/common_engine/application.cpp \
		src/common_engine/screen.cpp \
		src/common_engine/graphics.cpp \
		src/mainwindow.cpp \
		src/main.cpp \
		src/view.cpp \
		src/common_engine/entity.cpp \
		src/common_engine/world.cpp \
		src/common_engine/shape.cpp \
		src/common_engine/cylinder.cpp \
		src/common_engine/range.cpp \
		src/common_engine/physicsentity.cpp \
		src/common_engine/staticphysicsentity.cpp \
		src/game/minecraftapp.cpp \
		src/game/minecraftmainmenu.cpp \
		src/game/minecraftgamescreen.cpp \
		src/game/minecraftworld.cpp \
		src/voxel_engine/chunk.cpp \
		src/voxel_engine/voxel.cpp \
		src/game/minecraftgrassvoxel.cpp \
		src/game/minecraftchunk.cpp \
		src/common_engine/noisegenerator.cpp \
		src/voxel_engine/voxelmanager.cpp \
		src/game/minecraftvoxelmanager.cpp \
		src/game/minecraftglassvoxel.cpp \
		src/game/minecrafticevoxel.cpp \
		src/common_engine/aab.cpp \
		src/common_engine/ray.cpp \
		src/game/minecraftcow.cpp \
		src/game/minecraftreedvoxel.cpp \
		src/game/minecraftgoal.cpp \
		src/game/minecraftendscreen.cpp \
		src/common_engine/perlinnoise.cpp \
		src/common_engine/resourceloader.cpp \
		src/game/minecraftbarkvoxel.cpp \
		src/game/minecraftleafvoxel.cpp \
		src/game/minecraftwatervoxel.cpp \
		src/game/minecraftflowervoxel.cpp \
		src/game/minecrafttallgrassvoxel.cpp \
		src/game/minecraftlightbarkvoxel.cpp \
		src/game/minecraftopaqueleafvoxel.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_view.cpp
OBJECTS       = camera.o \
		player.o \
		application.o \
		screen.o \
		graphics.o \
		mainwindow.o \
		main.o \
		view.o \
		entity.o \
		world.o \
		shape.o \
		cylinder.o \
		range.o \
		physicsentity.o \
		staticphysicsentity.o \
		minecraftapp.o \
		minecraftmainmenu.o \
		minecraftgamescreen.o \
		minecraftworld.o \
		chunk.o \
		voxel.o \
		minecraftgrassvoxel.o \
		minecraftchunk.o \
		noisegenerator.o \
		voxelmanager.o \
		minecraftvoxelmanager.o \
		minecraftglassvoxel.o \
		minecrafticevoxel.o \
		aab.o \
		ray.o \
		minecraftcow.o \
		minecraftreedvoxel.o \
		minecraftgoal.o \
		minecraftendscreen.o \
		perlinnoise.o \
		resourceloader.o \
		minecraftbarkvoxel.o \
		minecraftleafvoxel.o \
		minecraftwatervoxel.o \
		minecraftflowervoxel.o \
		minecrafttallgrassvoxel.o \
		minecraftlightbarkvoxel.o \
		minecraftopaqueleafvoxel.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_view.o
DIST          = fog.vert \
		fog.vert \
		fog.frag \
		../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		minecraft.pro src/common_engine/camera.h \
		src/common_engine/player.h \
		src/common_engine/application.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		src/mainwindow.h \
		src/main.h \
		src/common_engine/vector.h \
		src/view.h \
		src/common_engine/entity.h \
		src/common_engine/world.h \
		src/common_engine/shape.h \
		src/common_engine/cylinder.h \
		src/common_engine/range.h \
		src/common_engine/physicsentity.h \
		src/common_engine/staticphysicsentity.h \
		src/game/minecraftapp.h \
		src/game/minecraftmainmenu.h \
		src/game/minecraftgamescreen.h \
		src/game/minecraftworld.h \
		src/voxel_engine/chunk.h \
		src/voxel_engine/voxel.h \
		src/game/minecraftgrassvoxel.h \
		src/game/minecraftchunk.h \
		src/common_engine/noisegenerator.h \
		src/voxel_engine/voxelmanager.h \
		src/game/minecraftvoxelmanager.h \
		src/game/minecraftglassvoxel.h \
		src/game/minecrafticevoxel.h \
		src/common_engine/aab.h \
		src/common_engine/ray.h \
		src/game/minecraftcow.h \
		src/game/minecraftreedvoxel.h \
		src/game/minecraftgoal.h \
		src/game/minecraftendscreen.h \
		src/common_engine/perlinnoise.h \
		src/common_engine/resourceloader.h \
		src/common_engine/glm.h \
		src/game/minecraftbarkvoxel.h \
		src/game/minecraftleafvoxel.h \
		src/game/minecraftwatervoxel.h \
		src/game/minecraftflowervoxel.h \
		src/game/minecrafttallgrassvoxel.h \
		src/game/minecraftlightbarkvoxel.h \
		src/game/minecraftopaqueleafvoxel.h src/common_engine/camera.cpp \
		src/common_engine/player.cpp \
		src/common_engine/application.cpp \
		src/common_engine/screen.cpp \
		src/common_engine/graphics.cpp \
		src/mainwindow.cpp \
		src/main.cpp \
		src/view.cpp \
		src/common_engine/entity.cpp \
		src/common_engine/world.cpp \
		src/common_engine/shape.cpp \
		src/common_engine/cylinder.cpp \
		src/common_engine/range.cpp \
		src/common_engine/physicsentity.cpp \
		src/common_engine/staticphysicsentity.cpp \
		src/game/minecraftapp.cpp \
		src/game/minecraftmainmenu.cpp \
		src/game/minecraftgamescreen.cpp \
		src/game/minecraftworld.cpp \
		src/voxel_engine/chunk.cpp \
		src/voxel_engine/voxel.cpp \
		src/game/minecraftgrassvoxel.cpp \
		src/game/minecraftchunk.cpp \
		src/common_engine/noisegenerator.cpp \
		src/voxel_engine/voxelmanager.cpp \
		src/game/minecraftvoxelmanager.cpp \
		src/game/minecraftglassvoxel.cpp \
		src/game/minecrafticevoxel.cpp \
		src/common_engine/aab.cpp \
		src/common_engine/ray.cpp \
		src/game/minecraftcow.cpp \
		src/game/minecraftreedvoxel.cpp \
		src/game/minecraftgoal.cpp \
		src/game/minecraftendscreen.cpp \
		src/common_engine/perlinnoise.cpp \
		src/common_engine/resourceloader.cpp \
		src/game/minecraftbarkvoxel.cpp \
		src/game/minecraftleafvoxel.cpp \
		src/game/minecraftwatervoxel.cpp \
		src/game/minecraftflowervoxel.cpp \
		src/game/minecrafttallgrassvoxel.cpp \
		src/game/minecraftlightbarkvoxel.cpp \
		src/game/minecraftopaqueleafvoxel.cpp
QMAKE_TARGET  = warmup
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = warmup.app/Contents/MacOS/warmup

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d warmup.app/Contents/MacOS/ || mkdir -p warmup.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: minecraft.pro ../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		minecraft.pro \
		resources.qrc \
		/Users/veenavignale/Qt/5.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/veenavignale/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/veenavignale/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/veenavignale/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile minecraft.pro
../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt.prf:
../../Qt/5.4/clang_64/mkspecs/features/resources.prf:
../../Qt/5.4/clang_64/mkspecs/features/moc.prf:
../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.4/clang_64/mkspecs/features/uic.prf:
../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
minecraft.pro:
resources.qrc:
/Users/veenavignale/Qt/5.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/veenavignale/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/veenavignale/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/veenavignale/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile minecraft.pro

qmake_all: FORCE

warmup.app/Contents/PkgInfo: 
	@test -d warmup.app/Contents || mkdir -p warmup.app/Contents
	@$(DEL_FILE) warmup.app/Contents/PkgInfo
	@echo "APPL????" >warmup.app/Contents/PkgInfo
warmup.app/Contents/Resources/empty.lproj: 
	@test -d warmup.app/Contents/Resources || mkdir -p warmup.app/Contents/Resources
	@touch warmup.app/Contents/Resources/empty.lproj
	
warmup.app/Contents/Info.plist: 
	@test -d warmup.app/Contents || mkdir -p warmup.app/Contents
	@$(DEL_FILE) warmup.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.warmup,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,warmup,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >warmup.app/Contents/Info.plist

all: Makefile \
		warmup.app/Contents/PkgInfo \
		warmup.app/Contents/Resources/empty.lproj \
		warmup.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/common_engine/camera.h src/common_engine/player.h src/common_engine/application.h src/common_engine/screen.h src/common_engine/graphics.h src/mainwindow.h src/main.h src/common_engine/vector.h src/view.h src/common_engine/entity.h src/common_engine/world.h src/common_engine/shape.h src/common_engine/cylinder.h src/common_engine/range.h src/common_engine/physicsentity.h src/common_engine/staticphysicsentity.h src/game/minecraftapp.h src/game/minecraftmainmenu.h src/game/minecraftgamescreen.h src/game/minecraftworld.h src/voxel_engine/chunk.h src/voxel_engine/voxel.h src/game/minecraftgrassvoxel.h src/game/minecraftchunk.h src/common_engine/noisegenerator.h src/voxel_engine/voxelmanager.h src/game/minecraftvoxelmanager.h src/game/minecraftglassvoxel.h src/game/minecrafticevoxel.h src/common_engine/aab.h src/common_engine/ray.h src/game/minecraftcow.h src/game/minecraftreedvoxel.h src/game/minecraftgoal.h src/game/minecraftendscreen.h src/common_engine/perlinnoise.h src/common_engine/resourceloader.h src/common_engine/glm.h src/game/minecraftbarkvoxel.h src/game/minecraftleafvoxel.h src/game/minecraftwatervoxel.h src/game/minecraftflowervoxel.h src/game/minecrafttallgrassvoxel.h src/game/minecraftlightbarkvoxel.h src/game/minecraftopaqueleafvoxel.h $(DISTDIR)/
	$(COPY_FILE) --parents src/common_engine/camera.cpp src/common_engine/player.cpp src/common_engine/application.cpp src/common_engine/screen.cpp src/common_engine/graphics.cpp src/mainwindow.cpp src/main.cpp src/view.cpp src/common_engine/entity.cpp src/common_engine/world.cpp src/common_engine/shape.cpp src/common_engine/cylinder.cpp src/common_engine/range.cpp src/common_engine/physicsentity.cpp src/common_engine/staticphysicsentity.cpp src/game/minecraftapp.cpp src/game/minecraftmainmenu.cpp src/game/minecraftgamescreen.cpp src/game/minecraftworld.cpp src/voxel_engine/chunk.cpp src/voxel_engine/voxel.cpp src/game/minecraftgrassvoxel.cpp src/game/minecraftchunk.cpp src/common_engine/noisegenerator.cpp src/voxel_engine/voxelmanager.cpp src/game/minecraftvoxelmanager.cpp src/game/minecraftglassvoxel.cpp src/game/minecrafticevoxel.cpp src/common_engine/aab.cpp src/common_engine/ray.cpp src/game/minecraftcow.cpp src/game/minecraftreedvoxel.cpp src/game/minecraftgoal.cpp src/game/minecraftendscreen.cpp src/common_engine/perlinnoise.cpp src/common_engine/resourceloader.cpp src/game/minecraftbarkvoxel.cpp src/game/minecraftleafvoxel.cpp src/game/minecraftwatervoxel.cpp src/game/minecraftflowervoxel.cpp src/game/minecrafttallgrassvoxel.cpp src/game/minecraftlightbarkvoxel.cpp src/game/minecraftopaqueleafvoxel.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r warmup.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		res/negxSunset.png \
		res/posxSunset.png \
		res/negz.png \
		res/posz.png \
		res/fog.frag \
		res/negy.png \
		res/posy.png \
		res/negx.png \
		res/posx.png \
		res/fog.vert \
		res/negzSunset.png \
		res/terrain.png \
		res/poszSunset.png \
		res/negySunset.png \
		res/posySunset.png
	/Users/veenavignale/Qt/5.4/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_view.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_view.cpp
moc_mainwindow.cpp: ../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		src/mainwindow.h
	/Users/veenavignale/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/veenavignale/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/veenavignale/Desktop/minecraft3 -I/Users/veenavignale/Desktop/minecraft3/src -I/Users/veenavignale/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/veenavignale/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/veenavignale/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/veenavignale/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/veenavignale/Qt/5.4/clang_64/lib src/mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: ../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/vector.h \
		src/common_engine/application.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/view.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/view.h
	/Users/veenavignale/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/veenavignale/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/veenavignale/Desktop/minecraft3 -I/Users/veenavignale/Desktop/minecraft3/src -I/Users/veenavignale/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/veenavignale/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/veenavignale/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/veenavignale/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/veenavignale/Qt/5.4/clang_64/lib src/view.h -o moc_view.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: src/mainwindow.ui \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/vector.h \
		src/common_engine/application.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/view.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h
	/Users/veenavignale/Qt/5.4/clang_64/bin/uic src/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

camera.o: src/common_engine/camera.cpp src/common_engine/camera.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/voxel_engine/chunk.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/voxel_engine/voxelmanager.h \
		src/voxel_engine/voxel.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h \
		src/common_engine/ray.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/noisegenerator.h \
		src/common_engine/perlinnoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o src/common_engine/camera.cpp

player.o: src/common_engine/player.cpp src/common_engine/player.h \
		src/common_engine/camera.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/voxel_engine/chunk.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/voxel_engine/voxelmanager.h \
		src/voxel_engine/voxel.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h \
		src/common_engine/ray.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/noisegenerator.h \
		src/common_engine/perlinnoise.h \
		src/common_engine/physicsentity.h \
		src/common_engine/cylinder.h \
		src/common_engine/aab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o src/common_engine/player.cpp

application.o: src/common_engine/application.cpp src/common_engine/application.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o application.o src/common_engine/application.cpp

screen.o: src/common_engine/screen.cpp src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o screen.o src/common_engine/screen.cpp

graphics.o: src/common_engine/graphics.cpp src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphics.o src/common_engine/graphics.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		ui_mainwindow.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/vector.h \
		src/common_engine/application.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

main.o: src/main.cpp ../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		src/mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

view.o: src/view.cpp src/view.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/vector.h \
		src/common_engine/application.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		src/game/minecraftapp.h \
		src/game/minecraftmainmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o src/view.cpp

entity.o: src/common_engine/entity.cpp src/common_engine/entity.h \
		src/common_engine/vector.h \
		src/common_engine/shape.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/common_engine/range.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entity.o src/common_engine/entity.cpp

world.o: src/common_engine/world.cpp src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o world.o src/common_engine/world.cpp

shape.o: src/common_engine/shape.cpp src/common_engine/shape.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/common_engine/range.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shape.o src/common_engine/shape.cpp

cylinder.o: src/common_engine/cylinder.cpp src/common_engine/cylinder.h \
		src/common_engine/shape.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/common_engine/range.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cylinder.o src/common_engine/cylinder.cpp

range.o: src/common_engine/range.cpp src/common_engine/range.h \
		src/common_engine/vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o range.o src/common_engine/range.cpp

physicsentity.o: src/common_engine/physicsentity.cpp src/common_engine/physicsentity.h \
		src/common_engine/entity.h \
		src/common_engine/vector.h \
		src/common_engine/shape.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/common_engine/range.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o physicsentity.o src/common_engine/physicsentity.cpp

staticphysicsentity.o: src/common_engine/staticphysicsentity.cpp src/common_engine/staticphysicsentity.h \
		src/common_engine/physicsentity.h \
		src/common_engine/entity.h \
		src/common_engine/vector.h \
		src/common_engine/shape.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/common_engine/range.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o staticphysicsentity.o src/common_engine/staticphysicsentity.cpp

minecraftapp.o: src/game/minecraftapp.cpp src/game/minecraftapp.h \
		src/common_engine/application.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftapp.o src/game/minecraftapp.cpp

minecraftmainmenu.o: src/game/minecraftmainmenu.cpp src/game/minecraftmainmenu.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/game/minecraftgamescreen.h \
		src/game/minecraftworld.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h \
		src/voxel_engine/chunk.h \
		src/voxel_engine/voxelmanager.h \
		src/voxel_engine/voxel.h \
		src/common_engine/ray.h \
		src/common_engine/camera.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/noisegenerator.h \
		src/common_engine/perlinnoise.h \
		src/game/minecraftgrassvoxel.h \
		src/common_engine/player.h \
		src/common_engine/physicsentity.h \
		src/common_engine/cylinder.h \
		src/common_engine/aab.h \
		src/game/minecraftcow.h \
		src/game/minecraftgoal.h \
		src/game/minecraftchunk.h \
		src/game/minecraftvoxelmanager.h \
		src/game/minecraftwatervoxel.h \
		src/game/minecraftglassvoxel.h \
		src/game/minecraftbarkvoxel.h \
		src/game/minecraftleafvoxel.h \
		src/game/minecrafticevoxel.h \
		src/game/minecraftreedvoxel.h \
		src/game/minecraftflowervoxel.h \
		src/game/minecrafttallgrassvoxel.h \
		src/game/minecraftlightbarkvoxel.h \
		src/game/minecraftopaqueleafvoxel.h \
		src/game/minecraftendscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftmainmenu.o src/game/minecraftmainmenu.cpp

minecraftgamescreen.o: src/game/minecraftgamescreen.cpp src/game/minecraftgamescreen.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/game/minecraftworld.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h \
		src/voxel_engine/chunk.h \
		src/voxel_engine/voxelmanager.h \
		src/voxel_engine/voxel.h \
		src/common_engine/ray.h \
		src/common_engine/camera.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/noisegenerator.h \
		src/common_engine/perlinnoise.h \
		src/game/minecraftgrassvoxel.h \
		src/common_engine/player.h \
		src/common_engine/physicsentity.h \
		src/common_engine/cylinder.h \
		src/common_engine/aab.h \
		src/game/minecraftcow.h \
		src/game/minecraftgoal.h \
		src/game/minecraftchunk.h \
		src/game/minecraftvoxelmanager.h \
		src/game/minecraftwatervoxel.h \
		src/game/minecraftglassvoxel.h \
		src/game/minecraftbarkvoxel.h \
		src/game/minecraftleafvoxel.h \
		src/game/minecrafticevoxel.h \
		src/game/minecraftreedvoxel.h \
		src/game/minecraftflowervoxel.h \
		src/game/minecrafttallgrassvoxel.h \
		src/game/minecraftlightbarkvoxel.h \
		src/game/minecraftopaqueleafvoxel.h \
		src/game/minecraftendscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftgamescreen.o src/game/minecraftgamescreen.cpp

minecraftworld.o: src/game/minecraftworld.cpp src/game/minecraftworld.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/screen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h \
		src/voxel_engine/chunk.h \
		src/voxel_engine/voxelmanager.h \
		src/voxel_engine/voxel.h \
		src/common_engine/ray.h \
		src/common_engine/camera.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/noisegenerator.h \
		src/common_engine/perlinnoise.h \
		src/game/minecraftgrassvoxel.h \
		src/common_engine/player.h \
		src/common_engine/physicsentity.h \
		src/common_engine/cylinder.h \
		src/common_engine/aab.h \
		src/game/minecraftcow.h \
		src/game/minecraftgoal.h \
		src/game/minecraftchunk.h \
		src/game/minecraftvoxelmanager.h \
		src/game/minecraftwatervoxel.h \
		src/game/minecraftglassvoxel.h \
		src/game/minecraftbarkvoxel.h \
		src/game/minecraftleafvoxel.h \
		src/game/minecrafticevoxel.h \
		src/game/minecraftreedvoxel.h \
		src/game/minecraftflowervoxel.h \
		src/game/minecrafttallgrassvoxel.h \
		src/game/minecraftlightbarkvoxel.h \
		src/game/minecraftopaqueleafvoxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftworld.o src/game/minecraftworld.cpp

chunk.o: src/voxel_engine/chunk.cpp src/voxel_engine/chunk.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/voxel_engine/voxelmanager.h \
		src/voxel_engine/voxel.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h \
		src/common_engine/ray.h \
		src/common_engine/camera.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/noisegenerator.h \
		src/common_engine/perlinnoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chunk.o src/voxel_engine/chunk.cpp

voxel.o: src/voxel_engine/voxel.cpp src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o voxel.o src/voxel_engine/voxel.cpp

minecraftgrassvoxel.o: src/game/minecraftgrassvoxel.cpp src/game/minecraftgrassvoxel.h \
		src/common_engine/entity.h \
		src/common_engine/vector.h \
		src/common_engine/shape.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/common_engine/range.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/voxel_engine/voxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftgrassvoxel.o src/game/minecraftgrassvoxel.cpp

minecraftchunk.o: src/game/minecraftchunk.cpp src/game/minecraftchunk.h \
		src/voxel_engine/chunk.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/voxel_engine/voxelmanager.h \
		src/voxel_engine/voxel.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h \
		src/common_engine/ray.h \
		src/common_engine/camera.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/noisegenerator.h \
		src/common_engine/perlinnoise.h \
		src/game/minecraftworld.h \
		src/game/minecraftgrassvoxel.h \
		src/common_engine/player.h \
		src/common_engine/physicsentity.h \
		src/common_engine/cylinder.h \
		src/common_engine/aab.h \
		src/game/minecraftcow.h \
		src/game/minecraftgoal.h \
		src/game/minecraftvoxelmanager.h \
		src/game/minecraftwatervoxel.h \
		src/game/minecraftglassvoxel.h \
		src/game/minecraftbarkvoxel.h \
		src/game/minecraftleafvoxel.h \
		src/game/minecrafticevoxel.h \
		src/game/minecraftreedvoxel.h \
		src/game/minecraftflowervoxel.h \
		src/game/minecrafttallgrassvoxel.h \
		src/game/minecraftlightbarkvoxel.h \
		src/game/minecraftopaqueleafvoxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftchunk.o src/game/minecraftchunk.cpp

noisegenerator.o: src/common_engine/noisegenerator.cpp src/common_engine/noisegenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o noisegenerator.o src/common_engine/noisegenerator.cpp

voxelmanager.o: src/voxel_engine/voxelmanager.cpp src/voxel_engine/voxelmanager.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/voxel_engine/voxel.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h \
		src/common_engine/ray.h \
		src/common_engine/camera.h \
		src/voxel_engine/chunk.h \
		src/common_engine/noisegenerator.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/perlinnoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o voxelmanager.o src/voxel_engine/voxelmanager.cpp

minecraftvoxelmanager.o: src/game/minecraftvoxelmanager.cpp src/game/minecraftvoxelmanager.h \
		src/voxel_engine/voxelmanager.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/voxel_engine/voxel.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h \
		src/common_engine/ray.h \
		src/common_engine/camera.h \
		src/voxel_engine/chunk.h \
		src/common_engine/noisegenerator.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/perlinnoise.h \
		src/game/minecraftgrassvoxel.h \
		src/game/minecraftwatervoxel.h \
		src/game/minecraftglassvoxel.h \
		src/game/minecraftbarkvoxel.h \
		src/game/minecraftleafvoxel.h \
		src/game/minecrafticevoxel.h \
		src/game/minecraftreedvoxel.h \
		src/game/minecraftflowervoxel.h \
		src/game/minecrafttallgrassvoxel.h \
		src/game/minecraftchunk.h \
		src/game/minecraftworld.h \
		src/common_engine/player.h \
		src/common_engine/physicsentity.h \
		src/common_engine/cylinder.h \
		src/common_engine/aab.h \
		src/game/minecraftcow.h \
		src/game/minecraftgoal.h \
		src/game/minecraftlightbarkvoxel.h \
		src/game/minecraftopaqueleafvoxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftvoxelmanager.o src/game/minecraftvoxelmanager.cpp

minecraftglassvoxel.o: src/game/minecraftglassvoxel.cpp src/game/minecraftglassvoxel.h \
		src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftglassvoxel.o src/game/minecraftglassvoxel.cpp

minecrafticevoxel.o: src/game/minecrafticevoxel.cpp src/game/minecrafticevoxel.h \
		src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecrafticevoxel.o src/game/minecrafticevoxel.cpp

aab.o: src/common_engine/aab.cpp src/common_engine/aab.h \
		src/common_engine/shape.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/common_engine/range.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aab.o src/common_engine/aab.cpp

ray.o: src/common_engine/ray.cpp src/common_engine/ray.h \
		src/common_engine/vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ray.o src/common_engine/ray.cpp

minecraftcow.o: src/game/minecraftcow.cpp src/game/minecraftcow.h \
		src/common_engine/physicsentity.h \
		src/common_engine/entity.h \
		src/common_engine/vector.h \
		src/common_engine/shape.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/common_engine/range.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/common_engine/aab.h \
		src/common_engine/cylinder.h \
		src/game/minecraftworld.h \
		src/voxel_engine/chunk.h \
		src/voxel_engine/voxelmanager.h \
		src/voxel_engine/voxel.h \
		src/common_engine/ray.h \
		src/common_engine/camera.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/noisegenerator.h \
		src/common_engine/perlinnoise.h \
		src/game/minecraftgrassvoxel.h \
		src/common_engine/player.h \
		src/game/minecraftgoal.h \
		src/game/minecraftchunk.h \
		src/game/minecraftvoxelmanager.h \
		src/game/minecraftwatervoxel.h \
		src/game/minecraftglassvoxel.h \
		src/game/minecraftbarkvoxel.h \
		src/game/minecraftleafvoxel.h \
		src/game/minecrafticevoxel.h \
		src/game/minecraftreedvoxel.h \
		src/game/minecraftflowervoxel.h \
		src/game/minecrafttallgrassvoxel.h \
		src/game/minecraftlightbarkvoxel.h \
		src/game/minecraftopaqueleafvoxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftcow.o src/game/minecraftcow.cpp

minecraftreedvoxel.o: src/game/minecraftreedvoxel.cpp src/game/minecraftreedvoxel.h \
		src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftreedvoxel.o src/game/minecraftreedvoxel.cpp

minecraftgoal.o: src/game/minecraftgoal.cpp src/game/minecraftgoal.h \
		src/common_engine/physicsentity.h \
		src/common_engine/entity.h \
		src/common_engine/vector.h \
		src/common_engine/shape.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/common_engine/range.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/screen.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/game/minecraftworld.h \
		src/voxel_engine/chunk.h \
		src/voxel_engine/voxelmanager.h \
		src/voxel_engine/voxel.h \
		src/common_engine/ray.h \
		src/common_engine/camera.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/noisegenerator.h \
		src/common_engine/perlinnoise.h \
		src/game/minecraftgrassvoxel.h \
		src/common_engine/player.h \
		src/common_engine/cylinder.h \
		src/common_engine/aab.h \
		src/game/minecraftcow.h \
		src/game/minecraftchunk.h \
		src/game/minecraftvoxelmanager.h \
		src/game/minecraftwatervoxel.h \
		src/game/minecraftglassvoxel.h \
		src/game/minecraftbarkvoxel.h \
		src/game/minecraftleafvoxel.h \
		src/game/minecrafticevoxel.h \
		src/game/minecraftreedvoxel.h \
		src/game/minecraftflowervoxel.h \
		src/game/minecrafttallgrassvoxel.h \
		src/game/minecraftlightbarkvoxel.h \
		src/game/minecraftopaqueleafvoxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftgoal.o src/game/minecraftgoal.cpp

minecraftendscreen.o: src/game/minecraftendscreen.cpp src/game/minecraftendscreen.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		src/common_engine/vector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		src/game/minecraftgamescreen.h \
		src/common_engine/screen.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		src/view.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/common_engine/application.h \
		src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		src/game/minecraftworld.h \
		src/common_engine/world.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		src/common_engine/entity.h \
		src/common_engine/shape.h \
		src/common_engine/range.h \
		src/voxel_engine/chunk.h \
		src/voxel_engine/voxelmanager.h \
		src/voxel_engine/voxel.h \
		src/common_engine/ray.h \
		src/common_engine/camera.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		src/common_engine/noisegenerator.h \
		src/common_engine/perlinnoise.h \
		src/game/minecraftgrassvoxel.h \
		src/common_engine/player.h \
		src/common_engine/physicsentity.h \
		src/common_engine/cylinder.h \
		src/common_engine/aab.h \
		src/game/minecraftcow.h \
		src/game/minecraftgoal.h \
		src/game/minecraftchunk.h \
		src/game/minecraftvoxelmanager.h \
		src/game/minecraftwatervoxel.h \
		src/game/minecraftglassvoxel.h \
		src/game/minecraftbarkvoxel.h \
		src/game/minecraftleafvoxel.h \
		src/game/minecrafticevoxel.h \
		src/game/minecraftreedvoxel.h \
		src/game/minecraftflowervoxel.h \
		src/game/minecrafttallgrassvoxel.h \
		src/game/minecraftlightbarkvoxel.h \
		src/game/minecraftopaqueleafvoxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftendscreen.o src/game/minecraftendscreen.cpp

perlinnoise.o: src/common_engine/perlinnoise.cpp src/common_engine/perlinnoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o perlinnoise.o src/common_engine/perlinnoise.cpp

resourceloader.o: src/common_engine/resourceloader.cpp src/common_engine/resourceloader.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		src/common_engine/glm.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resourceloader.o src/common_engine/resourceloader.cpp

minecraftbarkvoxel.o: src/game/minecraftbarkvoxel.cpp src/game/minecraftbarkvoxel.h \
		src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftbarkvoxel.o src/game/minecraftbarkvoxel.cpp

minecraftleafvoxel.o: src/game/minecraftleafvoxel.cpp src/game/minecraftleafvoxel.h \
		src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftleafvoxel.o src/game/minecraftleafvoxel.cpp

minecraftwatervoxel.o: src/game/minecraftwatervoxel.cpp src/game/minecraftwatervoxel.h \
		src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftwatervoxel.o src/game/minecraftwatervoxel.cpp

minecraftflowervoxel.o: src/game/minecraftflowervoxel.cpp src/game/minecraftflowervoxel.h \
		src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftflowervoxel.o src/game/minecraftflowervoxel.cpp

minecrafttallgrassvoxel.o: src/game/minecrafttallgrassvoxel.cpp src/game/minecrafttallgrassvoxel.h \
		src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecrafttallgrassvoxel.o src/game/minecrafttallgrassvoxel.cpp

minecraftlightbarkvoxel.o: src/game/minecraftlightbarkvoxel.cpp src/game/minecraftlightbarkvoxel.h \
		src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftlightbarkvoxel.o src/game/minecraftlightbarkvoxel.cpp

minecraftopaqueleafvoxel.o: src/game/minecraftopaqueleafvoxel.cpp src/game/minecraftopaqueleafvoxel.h \
		src/voxel_engine/voxel.h \
		src/common_engine/vector.h \
		src/common_engine/graphics.h \
		../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraftopaqueleafvoxel.o src/game/minecraftopaqueleafvoxel.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

